### ISSUE TITLE
Units of volume

### ISSUE THREAD

**Issue by keerthan2** [JoseLlorensRipolles/stockpile-volume-computation#1]
Hi. 
How do you know the volume is in m^3 ?. Is that information encoded in the point cloud ?.

**Comment by JoseLlorensRipolles** [comment]
> Hi. 
> How do you know the volume is in m^3 ?. Is that information encoded in the point cloud ?.

Yes. It is a very small stockpile I was using just for the notebook, so don't be surprised the numbers are so low. 😀

**Comment by keerthan2** [comment]
Cool thanks.
